# Generated by Django 3.2.18 on 2023-03-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='../category_image_mktm2q', upload_to='images/'),
        ),
    ]
