# Generated by Django 3.2.18 on 2023-03-15 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_image'),
        ('private_screenshots', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatescreenshot',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_scrt_count', to='category.category'),
        ),
    ]
